name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: ubuntu-latest
    env:
      llvm_path: "${{ github.workspace }}/llvm-mingw"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install \
            build-essential p7zip cmake ninja-build pkg-config autoconf automake autoconf-archive make texinfo bison flex m4 libtool libx11-dev
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64.tar.xz
          tar -xf llvm-mingw-*.tar.xz
          mv llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64 llvm-mingw
          
      - name: Setup a new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch
        with:
          vcpkgGitCommitId: 'b322364f06308bdd24823f9d8f03fe0cc86fd46f'

      - name: Build TL host tools
        if: steps.cache-tl-host-bin.outputs.cache-hit != 'true'
        run: |
          wget https://mirrors.ctan.org/systems/texlive/Source/texlive-20240311-source.tar.xz
          tar xf texlive-20240311-source.tar.xz
          cd texlive-20240311-source
          mkdir build-linux
          cd build-linux
          ../configure --disable-all-pkgs --enable-web2c 
          make -j $(nproc) || true
          mkdir -p ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/tangle ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/ctangle ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/otangle ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/himktables ${{ github.workspace }}/tl-host-bin
          cp ./texk/web2c/tie ${{ github.workspace }}/tl-host-bin

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tl-host-bin
          path: tl-host-bin
